INSERT INTO TB_ARTISTA(NOME, NACIONALIDADE) VALUES ('Michael Jackson', 'USA');
INSERT INTO TB_ARTISTA(NOME, NACIONALIDADE) VALUES ('Ray Charles', 'USA');

INSERT INTO TB_ALBUM(NOME, ANO) VALUES ('Bad', 1987);
INSERT INTO TB_ALBUM(NOME, ANO) VALUES ('Thriller', 1982);
INSERT INTO TB_ALBUM(NOME, ANO) VALUES ('We are the world', 1985);

INSERT INTO TB_ARTISTA_ALBUM(ARTISTA_ID, ALBUM_ID) VALUES(1, 1);
INSERT INTO TB_ARTISTA_ALBUM(ARTISTA_ID, ALBUM_ID) VALUES(1, 2);
INSERT INTO TB_ARTISTA_ALBUM(ARTISTA_ID, ALBUM_ID) VALUES(1, 3);
INSERT INTO TB_ARTISTA_ALBUM(ARTISTA_ID, ALBUM_ID) VALUES(2, 3);