INSERT INTO TB_ARTISTA(NOME, NACIONALIDADE) VALUES ('Michael Jackson', 'USA');
INSERT INTO TB_ARTISTA(NOME, NACIONALIDADE) VALUES ('Ray Charles', 'USA');

INSERT INTO TB_ALBUM(NOME, ANO) VALUES ('Bad', 1987);
INSERT INTO TB_ALBUM(NOME, ANO) VALUES ('Thriller', 1982);
INSERT INTO TB_ALBUM(NOME, ANO) VALUES ('We are the world', 1985);

INSERT INTO TB_ARTISTA_ALBUM(ARTISTA_ID, ALBUM_ID) VALUES(1, 1);
INSERT INTO TB_ARTISTA_ALBUM(ARTISTA_ID, ALBUM_ID) VALUES(1, 2);
INSERT INTO TB_ARTISTA_ALBUM(ARTISTA_ID, ALBUM_ID) VALUES(1, 3);
INSERT INTO TB_ARTISTA_ALBUM(ARTISTA_ID, ALBUM_ID) VALUES(2, 3);

INSERT INTO TB_MUSICA(NOME, DURACAO) VALUES ('Smooth Criminal', 250);
INSERT INTO TB_MUSICA(NOME, DURACAO) VALUES ('Billie Jean', 300);
INSERT INTO TB_MUSICA(NOME, DURACAO) VALUES ('Beat it', 240);
INSERT INTO TB_MUSICA(NOME, DURACAO) VALUES ('We are the world', 390);

INSERT INTO TB_ARTISTA_MUSICA(ARTISTA_ID, MUSICA_ID) VALUES(1, 1);
INSERT INTO TB_ARTISTA_MUSICA(ARTISTA_ID, MUSICA_ID) VALUES(1, 2);
INSERT INTO TB_ARTISTA_MUSICA(ARTISTA_ID, MUSICA_ID) VALUES(1, 3);
INSERT INTO TB_ARTISTA_MUSICA(ARTISTA_ID, MUSICA_ID) VALUES(1, 4);
INSERT INTO TB_ARTISTA_MUSICA(ARTISTA_ID, MUSICA_ID) VALUES(2, 4);